### PR TITLE
feat: enable CI for pull request

### PR DESCRIPTION
**Pull request by dyxushuai**
Related #75 #76
+r @Wollac

### CODE REVIEW

**Comment by flaub** [comment]
Could you provide more context with what this change is for? I think we should avoid the whitespace changes and use a common formatter/lint tool to ensure different users don't introduce different whitespace.

**Comment by dyxushuai** [comment]
> Could you provide more context with what this change is for? I think we should avoid the whitespace changes and use a common formatter/lint tool to ensure different users don't introduce different whitespace.

Related to this pr https://github.com/risc0/zeth/pull/75#issuecomment-1896273565

**Comment by dyxushuai** [comment]
> I think we should avoid the whitespace changes and use a common formatter/lint tool to ensure different users don't introduce different whitespace.

Yeah, I agree. This file was formatted by vscode github action official extension [marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions)

**Comment by dyxushuai** [comment]
> Yeah, I agree. This file was formatted by the suggestion of this [issue](https://github.com/github/vscode-github-actions/issues/195) in official vscode github action extension [marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions).

FYI, https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

**Comment by flaub** [comment]
If we want to start enforcing a style on these files, then we need to have a CI check to ensure that the file can't be landed in a bad style.

**Comment by dyxushuai** [comment]
good idea, using CI lints CI file, haha

**Comment by dyxushuai** [comment]
> good idea, using CI lints CI file, haha

@flaub I added [`yamllint`](https://github.com/adrienverge/yamllint) for CI files and tested it locally. It worked as expected.

**Comment by hashcashier** [comment]
@dyxushuai @flaub @intoverflow @Wollac 
Closing this stale PR

**Pull request closed without merging**
